<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Veda Jenetty Immaraj">

<title>Jenetty Immaraj - Blog</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Jenetty Immaraj</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html" rel="" target="">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./resume.html" rel="" target="">
 <span class="menu-text">Resume</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./Projects.html" rel="" target="">
 <span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./Blog.html" rel="" target="" aria-current="page">
 <span class="menu-text">Blog</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools ms-auto">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#unveiling-insights-a-journey-through-eda-with-the-mtcars-dataset" id="toc-unveiling-insights-a-journey-through-eda-with-the-mtcars-dataset" class="nav-link active" data-scroll-target="#unveiling-insights-a-journey-through-eda-with-the-mtcars-dataset"><strong>Unveiling Insights: A Journey through EDA with the ‘mtcars’ Dataset</strong></a></li>
  <li><a href="#step-1-loading-the-dataset" id="toc-step-1-loading-the-dataset" class="nav-link" data-scroll-target="#step-1-loading-the-dataset"><strong>Step 1: Loading the Dataset</strong></a></li>
  <li><a href="#step-2-univariate-analysis" id="toc-step-2-univariate-analysis" class="nav-link" data-scroll-target="#step-2-univariate-analysis"><strong>Step 2: Univariate Analysis</strong></a>
  <ul class="collapse">
  <li><a href="#summary-statistics" id="toc-summary-statistics" class="nav-link" data-scroll-target="#summary-statistics"><strong>Summary Statistics</strong></a></li>
  <li><a href="#mileage-distribution" id="toc-mileage-distribution" class="nav-link" data-scroll-target="#mileage-distribution"><strong>Mileage Distribution</strong></a></li>
  </ul></li>
  <li><a href="#step-3-bivariate-analysis" id="toc-step-3-bivariate-analysis" class="nav-link" data-scroll-target="#step-3-bivariate-analysis"><strong>Step 3: Bivariate Analysis</strong></a>
  <ul class="collapse">
  <li><a href="#scatter-plot-horsepower-vs.-mileage" id="toc-scatter-plot-horsepower-vs.-mileage" class="nav-link" data-scroll-target="#scatter-plot-horsepower-vs.-mileage"><strong>Scatter Plot: Horsepower vs.&nbsp;Mileage</strong></a></li>
  <li><a href="#correlation-matrix" id="toc-correlation-matrix" class="nav-link" data-scroll-target="#correlation-matrix"><strong>Correlation Matrix</strong></a></li>
  </ul></li>
  <li><a href="#step-4-multivariate-analysis" id="toc-step-4-multivariate-analysis" class="nav-link" data-scroll-target="#step-4-multivariate-analysis"><strong>Step 4: Multivariate Analysis</strong></a>
  <ul class="collapse">
  <li><a href="#pairwise-scatterplot-matrix" id="toc-pairwise-scatterplot-matrix" class="nav-link" data-scroll-target="#pairwise-scatterplot-matrix"><strong>Pairwise Scatterplot Matrix</strong></a></li>
  <li><a href="#boxplot-mileage-distribution-by-number-of-cylinders" id="toc-boxplot-mileage-distribution-by-number-of-cylinders" class="nav-link" data-scroll-target="#boxplot-mileage-distribution-by-number-of-cylinders"><strong>Boxplot: Mileage Distribution by Number of Cylinders</strong></a></li>
  </ul></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion"><strong>Conclusion</strong></a></li>
  <li><a href="#closing-thoughts" id="toc-closing-thoughts" class="nav-link" data-scroll-target="#closing-thoughts"><strong>Closing Thoughts</strong></a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Blog</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Veda Jenetty Immaraj </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<section id="unveiling-insights-a-journey-through-eda-with-the-mtcars-dataset" class="level2">
<h2 class="anchored" data-anchor-id="unveiling-insights-a-journey-through-eda-with-the-mtcars-dataset"><strong>Unveiling Insights: A Journey through EDA with the ‘mtcars’ Dataset</strong></h2>
<p>Welcome to a fascinating exploration of the ‘mtcars’ dataset! In this blog post, we will embark on a journey through Exploratory Data Analysis (EDA) using R. The ‘mtcars’ dataset, a classic dataset in R, contains specifications and performance measures of various car models.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">"cars.jpg"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="cars.jpg" class="img-fluid"></p>
</div>
</div>
</section>
<section id="step-1-loading-the-dataset" class="level2">
<h2 class="anchored" data-anchor-id="step-1-loading-the-dataset"><strong>Step 1: Loading the Dataset</strong></h2>
<p>Let’s start by loading the ‘mtcars’ dataset into our R environment.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the mtcars dataset</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(mtcars)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The provided code snippet loads the ‘mtcars’ dataset, a built-in dataset available in R. This dataset contains information about various car models, including their specifications like miles per gallon (mpg), number of cylinders, horsepower, and more. By using the command data(mtcars), this code makes the ‘mtcars’ dataset available for analysis and manipulation within the R environment.</p>
</section>
<section id="step-2-univariate-analysis" class="level2">
<h2 class="anchored" data-anchor-id="step-2-univariate-analysis"><strong>Step 2: Univariate Analysis</strong></h2>
<section id="summary-statistics" class="level3">
<h3 class="anchored" data-anchor-id="summary-statistics"><strong>Summary Statistics</strong></h3>
<p>To gain an initial understanding of the dataset, let’s examine some summary statistics.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Display summary statistics</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mtcars)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      mpg             cyl             disp             hp       
 Min.   :10.40   Min.   :4.000   Min.   : 71.1   Min.   : 52.0  
 1st Qu.:15.43   1st Qu.:4.000   1st Qu.:120.8   1st Qu.: 96.5  
 Median :19.20   Median :6.000   Median :196.3   Median :123.0  
 Mean   :20.09   Mean   :6.188   Mean   :230.7   Mean   :146.7  
 3rd Qu.:22.80   3rd Qu.:8.000   3rd Qu.:326.0   3rd Qu.:180.0  
 Max.   :33.90   Max.   :8.000   Max.   :472.0   Max.   :335.0  
      drat             wt             qsec             vs        
 Min.   :2.760   Min.   :1.513   Min.   :14.50   Min.   :0.0000  
 1st Qu.:3.080   1st Qu.:2.581   1st Qu.:16.89   1st Qu.:0.0000  
 Median :3.695   Median :3.325   Median :17.71   Median :0.0000  
 Mean   :3.597   Mean   :3.217   Mean   :17.85   Mean   :0.4375  
 3rd Qu.:3.920   3rd Qu.:3.610   3rd Qu.:18.90   3rd Qu.:1.0000  
 Max.   :4.930   Max.   :5.424   Max.   :22.90   Max.   :1.0000  
       am              gear            carb      
 Min.   :0.0000   Min.   :3.000   Min.   :1.000  
 1st Qu.:0.0000   1st Qu.:3.000   1st Qu.:2.000  
 Median :0.0000   Median :4.000   Median :2.000  
 Mean   :0.4062   Mean   :3.688   Mean   :2.812  
 3rd Qu.:1.0000   3rd Qu.:4.000   3rd Qu.:4.000  
 Max.   :1.0000   Max.   :5.000   Max.   :8.000  </code></pre>
</div>
</div>
<p>The provided code snippet showcases the functionality of R in analyzing the ‘mtcars’ dataset. With the help of the <strong><code>summary()</code></strong> function, this code efficiently presents a condensed summary of essential statistical metrics for each variable within the dataset.</p>
<p>By leveraging R’s <strong><code>summary()</code></strong> function, we gain insights into crucial statistics such as minimum and maximum values, median, quartiles, and means associated with every variable in the ‘mtcars’ dataset. Setting <strong><code>echo=TRUE</code></strong> allows the code and its resulting output to be displayed together, enabling clear visibility of both code execution and the summary statistics generated.</p>
<p>This simple yet powerful command provides a quick overview of the dataset’s key statistical measures, offering valuable insights into the range and distribution of the car attributes in the dataset.</p>
</section>
<section id="mileage-distribution" class="level3">
<h3 class="anchored" data-anchor-id="mileage-distribution"><strong>Mileage Distribution</strong></h3>
<p>Now, let’s visualize the distribution of mileage (‘mpg’) using a histogram.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualize distribution of mileage</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(mtcars<span class="sc">$</span>mpg, <span class="at">main =</span> <span class="st">"Distribution of Mileage (mpg)"</span>, <span class="at">xlab =</span> <span class="st">"Miles per Gallon"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Blog_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>In the provided code snippet, I’ve utilized R to craft a histogram that showcases the distribution pattern of mileage (measured in miles per gallon) from the ‘mtcars’ dataset. This histogram provides a visual representation of how often various mileage values occur across different car models.</p>
<p>By using the ‘hist()’ function, I’ve generated this histogram, emphasizing the x-axis as ‘Miles per Gallon’ and titling the plot as ‘Distribution of Mileage (mpg)’. This visualization effectively illustrates the spread and frequency of distinct mileage values within our dataset.</p>
<p>Notably, from the histogram, we can observe a notable peak in frequency within the 15-20 miles per gallon range, indicating that a significant number of car models in the dataset fall within this mileage range.</p>
</section>
</section>
<section id="step-3-bivariate-analysis" class="level2">
<h2 class="anchored" data-anchor-id="step-3-bivariate-analysis"><strong>Step 3: Bivariate Analysis</strong></h2>
<section id="scatter-plot-horsepower-vs.-mileage" class="level3">
<h3 class="anchored" data-anchor-id="scatter-plot-horsepower-vs.-mileage"><strong>Scatter Plot: Horsepower vs.&nbsp;Mileage</strong></h3>
<p>Let’s explore the relationship between horsepower (‘hp’) and mileage using a scatter plot.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Scatter plot for horsepower vs. mileage</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mtcars<span class="sc">$</span>hp, mtcars<span class="sc">$</span>mpg, <span class="at">main =</span> <span class="st">"Scatter Plot: Horsepower vs. Mileage"</span>, <span class="at">xlab =</span> <span class="st">"Horsepower"</span>, <span class="at">ylab =</span> <span class="st">"Miles per Gallon"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Blog_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>In this code snippet, I’ve generated a scatter plot using R. The plot visualizes the relationship between two key car attributes: horsepower and mileage (measured in miles per gallon, mpg).</p>
<p>The <strong><code>plot()</code></strong> function creates the scatter plot. I’ve specified <strong><code>mtcars$hp</code></strong> on the x-axis, representing the car’s horsepower, and <strong><code>mtcars$mpg</code></strong> on the y-axis, depicting the miles per gallon. Additionally, I’ve included a title for the plot (“Scatter Plot: Horsepower vs.&nbsp;Mileage”) using <strong><code>main</code></strong>, and labeled the x-axis as “Horsepower” and the y-axis as “Miles per Gallon” using <strong><code>xlab</code></strong> and <strong><code>ylab</code></strong> respectively.</p>
<p>This visualization allows us to understand the potential relationship between a car’s horsepower and its fuel efficiency, giving insight into how these factors might be correlated in the dataset.</p>
</section>
<section id="correlation-matrix" class="level3">
<h3 class="anchored" data-anchor-id="correlation-matrix"><strong>Correlation Matrix</strong></h3>
<p>Now, let’s quantify the relationships between mileage, horsepower, and weight using a correlation matrix.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Correlation matrix</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(mtcars[, <span class="fu">c</span>(<span class="st">"mpg"</span>, <span class="st">"hp"</span>, <span class="st">"wt"</span>)])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           mpg         hp         wt
mpg  1.0000000 -0.7761684 -0.8676594
hp  -0.7761684  1.0000000  0.6587479
wt  -0.8676594  0.6587479  1.0000000</code></pre>
</div>
</div>
<p>In this code snippet using R, I’ve computed a correlation matrix for specific attributes within the ‘mtcars’ dataset. The variables ‘mpg’ (miles per gallon), ‘hp’ (horsepower), and ‘wt’ (car weight) were chosen for this analysis.</p>
<p>The output of the correlation matrix reveals the relationship between these variables. Each number in the matrix represents the correlation coefficient between two attributes. A correlation coefficient ranges from -1 to 1, where:</p>
<ul>
<li><p>A value of 1 indicates a perfect positive correlation.</p></li>
<li><p>A value of -1 indicates a perfect negative correlation.</p></li>
<li><p>A value of 0 suggests no linear relationship between the variables.</p></li>
</ul>
<p>For instance, in this matrix:</p>
<ul>
<li><p>The correlation between ‘mpg’ and ‘hp’ is approximately -0.776, indicating a moderate negative correlation.</p></li>
<li><p>The correlation between ‘mpg’ and ‘wt’ is around -0.868, showing a strong negative relationship.</p></li>
<li><p>The correlation between ‘hp’ and ‘wt’ is about 0.659, representing a moderate positive correlation.</p></li>
</ul>
<p>This analysis helps to understand the interdependencies among these car attributes, providing insights into how changes in one attribute might affect others.</p>
</section>
</section>
<section id="step-4-multivariate-analysis" class="level2">
<h2 class="anchored" data-anchor-id="step-4-multivariate-analysis"><strong>Step 4: Multivariate Analysis</strong></h2>
<section id="pairwise-scatterplot-matrix" class="level3">
<h3 class="anchored" data-anchor-id="pairwise-scatterplot-matrix"><strong>Pairwise Scatterplot Matrix</strong></h3>
<p>Visualize relationships involving multiple variables with a pairwise scatterplot matrix.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Pairwise scatterplot matrix</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(mtcars[, <span class="fu">c</span>(<span class="st">"mpg"</span>, <span class="st">"hp"</span>, <span class="st">"wt"</span>, <span class="st">"disp"</span>)])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Blog_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>In the provided R code snippet, I’ve generated a pairwise scatterplot matrix using the ‘pairs()’ function for selected variables from the ‘mtcars’ dataset. The variables included for analysis are ‘mpg’ (miles per gallon), ‘hp’ (horsepower), ‘wt’ (car weight), and ‘disp’ (displacement).</p>
<p>This scatterplot matrix visually presents relationships among these specific car attributes by showcasing scatterplots of each variable against every other variable in the selected set. Each scatterplot represents the correlation or pattern between two attributes, offering a comprehensive view of their interactions.</p>
<p>The resulting output is a matrix of scatterplots arranged in a grid format, where the diagonal displays histograms showcasing the distribution of individual variables. The off-diagonal elements exhibit scatterplots illustrating the relationship between pairs of attributes.</p>
<p>This visual representation aids in identifying potential correlations, trends, or patterns among the selected car attributes, providing an intuitive overview of their interrelationships within the dataset.</p>
</section>
<section id="boxplot-mileage-distribution-by-number-of-cylinders" class="level3">
<h3 class="anchored" data-anchor-id="boxplot-mileage-distribution-by-number-of-cylinders"><strong>Boxplot: Mileage Distribution by Number of Cylinders</strong></h3>
<p>Explore how the number of cylinders (‘cyl’) influences mileage using a boxplot.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Boxplot by number of cylinders</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(mpg <span class="sc">~</span> cyl, <span class="at">data =</span> mtcars, <span class="at">main =</span> <span class="st">"Mileage Distribution by Number of Cylinders"</span>, <span class="at">xlab =</span> <span class="st">"Number of Cylinders"</span>, <span class="at">ylab =</span> <span class="st">"Miles per Gallon"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Blog_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>In this code segment using R, I’ve generated a boxplot visualization to explore the relationship between the number of cylinders in cars and their corresponding mileage (measured in miles per gallon, mpg).</p>
<p>The <strong><code>boxplot()</code></strong> function creates the graphical representation. By specifying <strong><code>mpg ~ cyl</code></strong>, I’ve directed the plot to display the distribution of mileage for different numbers of cylinders. The ‘mtcars’ dataset is utilized for this analysis.</p>
<p>The resulting boxplot visually compares the mileage distributions across various cylinder counts. The x-axis shows the number of cylinders in the cars, while the y-axis represents the miles per gallon achieved by each category. This visualization helps in understanding the variation in mileage concerning the different cylinder configurations, showcasing potential trends or differences in fuel efficiency based on the number of cylinders.</p>
<p>By observing the spread and median values depicted in the boxplot for each cylinder count category, we can gain insights into how the number of cylinders might impact the overall mileage performance of cars.</p>
</section>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion"><strong>Conclusion</strong></h2>
<p>In this journey through EDA with the ‘mtcars’ dataset, we uncovered valuable insights about the relationships between mileage, horsepower, and other specifications. Higher horsepower tends to correlate with lower mileage, and there’s significant variation in mileage based on the number of cylinders.</p>
</section>
<section id="closing-thoughts" class="level2">
<h2 class="anchored" data-anchor-id="closing-thoughts"><strong>Closing Thoughts</strong></h2>
<p>EDA is a powerful tool for gaining a deeper understanding of your data. I encourage you to apply these techniques to your own datasets and explore the fascinating stories they hold. Happy exploring!</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>